# Copied from: https://github.com/LagoLunatic/ooe/blob/main/.github/workflows/build.yml
name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false
      matrix:
        version: [A2DE]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Copy files to working directory
      run: cp -R /orig/* .

    - name: Extract ROM
      run: zig build extract

    - name: Delink ROM
      run: zig build delink
        
    - name: Generate objdiff config
      run: zig build objdiff
    
    - name: Compile all files
      run: zig build all

    - name: Generate objdiff report
      run: zig build report

    - name: Upload Report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/report.json